# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 06:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
