# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_checked',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='requester_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='requester_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_id',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='worker_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
