# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20170227_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hit_id',
            field=models.TextField(blank=True, default=''),
        ),
    ]
