# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_task_hit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('guild_name', models.TextField(blank=True, default='', null=True)),
                ('guild_creator_id', models.TextField(blank=True, default='', null=True)),
                ('guild_creator_type', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuildWorkerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('last_modified', models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('worker_name', models.TextField(blank=True, default='', null=True)),
                ('worker_id', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='guildworkermap',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guildworkermap_guild', to='taskapp.Worker'),
        ),
        migrations.AddField(
            model_name='guildworkermap',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guildworkermap_worker', to='taskapp.Worker'),
        ),
    ]
