# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20170404_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildworkermap',
            name='guild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guildworkermap_guild', to='taskapp.Guild'),
        ),
    ]
